"""
Generates standalone Python scripts for GPAW calculations.

The API server never imports GPAW directly — it writes a temp script
and shells out via ``mpirun gpaw python script.py``. This keeps the
worker process lightweight and avoids MPI compatibility issues.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from server.schemas import CalculateRequest


def _build_script(payload: dict) -> str:
    """Render a standalone Python script from the request payload dict.

    The script is **filesystem-free**: input JSON is embedded as a string
    constant, GPAW writes SCF output to stdout (``txt='-'``), and results
    are emitted to stdout delimited by ``===BEYONDLDA2_RESULT===`` markers.
    No files (input.json, output.json, .txt log) are written or read.
    """
    calc_type = payload["calculation_type"]
    label = payload.get("label", "gpaw-job")
    params = payload.get("parameters", {})

    # Build the kwargs dict for lda_plus_u constructor
    constructor_keys = {
        "xc", "hubbard_u", "magnetic_center", "spin_state",
        "planewave", "pwcut", "kmesh", "beta", "nmaxold", "weight",
        "maxcycl", "etol", "dentol", "eigentol", "symmetry",
        "temperature", "vdw", "charge", "efield", "high_ox",
        "spin_pol", "fixspin", "isMol", "magmoms", "nbands",
        "conv_bands", "dipcorr", "conv_default", "semicore",
        "kp_shift", "domain_parallel",
    }
    # Method-specific params (used in dispatch, not in constructor)
    method_params_map = {
        "local_opt": {"force_convergence"},
        "g0w0_gap": {"ecut", "ppa"},
        "absorption": {"ecut"},
    }
    method_params = method_params_map.get(calc_type, set())

    kwarg_entries = []
    method_kwarg_pairs = []
    for k, v in params.items():
        if v is None:
            continue
        if k in constructor_keys:
            if isinstance(v, bool):
                kwarg_entries.append(f'    "{k}": {str(v)},')
            elif isinstance(v, str):
                kwarg_entries.append(f'    "{k}": "{v}",')
            elif isinstance(v, list):
                kwarg_entries.append(f'    "{k}": {json.dumps(v)},')
            else:
                kwarg_entries.append(f'    "{k}": {v},')
        elif k in method_params:
            if isinstance(v, bool):
                method_kwarg_pairs.append(f'{k}={str(v)}')
            elif isinstance(v, str):
                method_kwarg_pairs.append(f'{k}="{v}"')
            else:
                method_kwarg_pairs.append(f'{k}={v}')
    kwargs_str = "\n".join(kwarg_entries)
    method_kwargs_str = ",\n        ".join(method_kwarg_pairs)

    # Dispatch per calculation type
    if method_kwargs_str:
        method_call_suffix = f",\n        {method_kwargs_str}"
    else:
        method_call_suffix = ""

    calc_dispatch = {
        "electronic_energy": (
            '    result["energy"] = dft.get_electronic_energy()'
        ),
        "ks_gap": (
            '    result["ks_gap"] = dft.get_ksgap()'
        ),
        "gllbsc_gap": (
            '    result["gllbsc_gap"] = dft.get_gllbscgap()'
        ),
        "g0w0_gap": (
            f'    gap = dft.get_g0w0gap({method_call_suffix})\n'
            '    result["g0w0_gap"] = gap'
        ),
        "local_opt": (
            f'    energy = dft.local_opt({method_call_suffix})\n'
            '    result["energy"] = energy\n'
            '    result["opt_geometry"] = dft.args["atoms"].positions.tolist()'
        ),
        "absorption": (
            f'    hw, abs_w = dft.get_absorption({method_call_suffix})\n'
            '    result["absorption_energies"] = hw.tolist()\n'
            '    result["absorption_spectrum"] = abs_w.tolist()'
        ),
        "phonon": (
            '    dft.phonon()\n'
            '    result["status"] = "phonon calculation completed"'
        ),
    }

    dispatch_block = calc_dispatch.get(calc_type, '    raise ValueError(f"Unknown calc type: {calc_type}")')

    # Serialise input payload as a Python-safe repr'd JSON string
    # repr() handles all escaping so the value slots safely into the f-string
    payload_json = json.dumps(payload, indent=2)
    payload_repr = repr(payload_json)

    script = f'''"""beyondLDA2 calculation — auto-generated by API server.
Filesystem-free: input embedded, GPAW txt='-', results on stdout.
"""
import sys
import json
import traceback
from datetime import datetime, timezone
from pathlib import Path

# Honor PYTHONPATH; fall back to inserting a parent-directory guess
_HERE = Path(__file__).resolve().parent
if "beyondLDA2" not in sys.modules and not any(
    "beyondLDA2" in p for p in sys.path
):
    for _guess in [
        _HERE,
        _HERE.parent,
        _HERE.parent.parent,
        _HERE.parent.parent / "beyondLDA2",
        _HERE.parent.parent.parent / "beyondLDA2",
        Path("/app"),
    ]:
        if (_guess / "beyondLDA2.py").exists():
            sys.path.insert(0, str(_guess))
            break

import gpaw
print(f"GPAW version: {{gpaw.__version__}}", flush=True)

from beyondLDA2 import lda_plus_u
from ase import Atoms
from tempfile import NamedTemporaryFile


def build_structure(data: dict) -> Atoms:
    """Build an ASE Atoms object from the request payload."""
    atoms_data = data.get("atoms")
    if atoms_data is None:
        from ase.io import read
        content = data["content"]
        fmt = data.get("format")
        with NamedTemporaryFile(mode="w", suffix="." + (fmt or "xyz"), delete=False) as f:
            f.write(content)
            tmp_path = f.name
        atoms = read(tmp_path, format=fmt)
        Path(tmp_path).unlink(missing_ok=True)
        return atoms

    symbols = [a["symbol"] for a in atoms_data]
    scaled_positions = [[a["x"], a["y"], a["z"]] for a in atoms_data]
    cell = data.get("cell")
    pbc = data.get("pbc")
    if pbc is None:
        pbc = [True, True, True]
    elif isinstance(pbc[0], int):
        pbc = [bool(p) for p in pbc]
    return Atoms(symbols=symbols, scaled_positions=scaled_positions, cell=cell, pbc=pbc)


def main():
    # --- Load input from embedded JSON (safe Python literal repr) ---
    _PAYLOAD_JSON = {payload_repr}
    payload = json.loads(_PAYLOAD_JSON)

    calc_type = payload["calculation_type"]
    params = payload.get("parameters", {{}})
    label = payload.get("label", "{label}")

    # --- Build atoms ---
    atoms = build_structure(payload.get("structure", {{}}))

    # --- Create calculator ---
    kwargs = {{
{kwargs_str}
    }}
    kwargs["atoms"] = atoms
    kwargs["fname"] = label
    kwargs["txt"] = "-"
    if kwargs.get("magnetic_center"):
        kwargs["magnetic_center"] = kwargs["magnetic_center"].capitalize()

    # Attach database if requested
    db_path = payload.get("database")
    if db_path:
        kwargs["database"] = str(_HERE / db_path) if "/" not in db_path else db_path

    dft = lda_plus_u(**kwargs)

    # --- Run calculation ---
    result = {{}}
    result["label"] = label
    result["calculation_type"] = calc_type
    result["gpaw_version"] = gpaw.__version__
    result["start_time"] = datetime.now(timezone.utc).isoformat()

{dispatch_block}

    # --- Store final atoms if modified (local_opt) ---
    if "opt_geometry" not in result:
        result["final_formula"] = atoms.get_chemical_formula()
        result["final_positions"] = atoms.positions.tolist()

    # --- Emit result to stdout (no files written) ---
    result["end_time"] = datetime.now(timezone.utc).isoformat()
    print("===BEYONDLDA2_RESULT===", flush=True)
    json.dump(result, sys.stdout, indent=2, default=str)
    print(flush=True)
    print("===END_BEYONDLDA2_RESULT===", flush=True)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        err = {{"error": str(e), "traceback": traceback.format_exc()}}
        print("===BEYONDLDA2_RESULT===", flush=True)
        json.dump(err, sys.stdout, indent=2, default=str)
        print(flush=True)
        print("===END_BEYONDLDA2_RESULT===", flush=True)
        sys.exit(1)
'''

    return script


def generate_script(req: CalculateRequest, label: str | None = None) -> str:
    """Generate a runnable Python script for the given request.

    The returned script is a standalone string that can be written to a
    temp directory and executed via ``mpirun gpaw python script.py``.
    """
    payload = req.model_dump(mode="json")
    if label:
        payload["label"] = label
    return _build_script(payload)


def write_job_dir(
    req: CalculateRequest,
    work_dir: str | Path,
    label: str | None = None,
) -> Path:
    """Write the script.py to a job directory.

    The input payload is embedded in the script itself — no input.json
    is written. The script writes nothing to disk (GPAW txt='-', results
    to stdout only).

    Returns the path to the job directory.
    """
    job_dir = Path(work_dir) / (label or "job")
    job_dir.mkdir(parents=True, exist_ok=True)

    payload = req.model_dump(mode="json")
    if label:
        payload["label"] = label

    # Write script (input payload is embedded inside)
    script = _build_script(payload)
    with open(job_dir / "script.py", "w") as f:
        f.write(script)

    return job_dir
